`use-deliver`: Review practical sessions
open-education-hub/methodology pull request #39
Opened 2023-09-06 18:40 UTC by molecula2788

2023-09-06 19:57 UTC, teodutu requested changes
You should incorporate the changes to drills and quizzes.

2023-09-06 19:57 UTC, teodutu commented on chapters/use-deliver/practical-sessions/reading/README.md
> +Therefore, for fields of study pertaining to the humanities, such as history or philosophy, we recommend using quizzes instead of drills as a form of practical activity.
All this paragraph needs to be reworded and expanded. Now we see drills as being all types of work that students may do and we split them between questions (previously named quizzes) and tasks (larger, more in-depth, require full solutions). You can see the differences highlighted in my PR: https://github.com/open-education-hub/methodology/pull/29

2023-09-07 10:31 UTC, RazvanN7 requested changes
what @teodutu said.

2023-09-11 18:27 UTC, teodutu approved these changes
Yeah I think it's clear enough now

2023-09-12 06:41 UTC, RazvanN7 approved these changes

2023-09-12 06:42 UTC, merged