infrastructure: add digital-rewards section
open-education-hub/methodology pull request #41
Opened 2023-09-07 16:06 UTC by RazvanN7

2023-09-07 16:07 UTC, RazvanN7 commented
cc @Jokeswar please review this and potentially add more information regarding the infrastructure and the guides to use the scripts you developed.

cc @gstefans as I have added some steps on how to obtain smileys, but those are not quite accurate.

2023-09-08 07:19 UTC, teodutu requested changes

2023-09-08 07:19 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
>  Reviewer: Mihai Băruța
```suggestion
```

2023-09-08 07:19 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
> +To enable the use of such teaching techniques, we offer an infrastructure for the use of cryptocurrency rewards that may be used to stimulate both learning and contributions to the educational conten
```suggestion
To enable such teaching techniques, we offer an infrastructure for cryptocurrency rewards with the purpose of stimulating learning and contributions to the educational content.
```

2023-09-08 07:19 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
> +We do not discuss the efectiveness of reward-based learning techniques, we simply provide the tools to implement such a system if an educator chooses to use it.
But shouldn't we discuss it? Why would someone use cryptocurrency if we don't make a case for it?

2023-09-08 07:19 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
> +- when a learner helps his peers (by publicly answering forum questions or helping them during practical sessions)
Or when the learner reviews a contribution

2023-09-08 07:19 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
> +Currently, we have implemented some scripts that make it easy to manually send smileycoin rewards.
You should add links to them here [1], and they ought to be detailed in the Infrastructure chapter.

[1] https://github.com/Jokeswar/smileycoin-api/wiki/Teaching-Assistan-Handbook

2023-09-08 08:49 UTC, Jokeswar reviewed
I am unsure if we need to detail the inner workings of the smiley coin reward system that we have. I am referring to some diagrams or extra details on the technical side. @RazvanN7 what do you think about that?

2023-09-08 08:49 UTC, Jokeswar commented on chapters/infrastructure/digital-rewards/reading/README.md
> +To account for these situations, we have developed an infrastructure that uses an educational cryptocurrency that may be awarded automatically or manually.
Should we add some links to the infrastructure repositories?

- https://github.com/Jokeswar/smileycoin-api
- https://github.com/Jokeswar/smileycoin-node

2023-12-27 14:47 UTC, teodutu requested changes
You're using SmileyCoins, smiley coins, Smiley Coins and smiley at the same time which makes the text look unproffessional. Be consistent.

2023-12-27 14:47 UTC, teodutu commented on chapters/infrastructure/digital-rewards/reading/README.md
> +For the awarding entity to be able to send the necessary smiley coins, it is required that the receivers wallet address is known.
```suggestion
For the awarding entity to be able to send the necessary smiley coins, it is required that the receivers wallet address be known.
```
although a relic, the subjunctive is still used

2023-12-27 16:33 UTC, teodutu approved these changes
Add "incentivize" and "cryptocurrenciee" to spellcheck's worldlist to silence thia workflow

2023-12-27 16:44 UTC, razvand commented
@teodutu , do one final check, please.

2023-12-27 16:50 UTC, teodutu approved these changes
Right, I had forgotten about `config.yaml`.

2023-12-27 16:58 UTC, merged